

```{r}

library(vegan)
library(ape)
library(ggplot2)
library(grid)
library(ggsci)

```



```{r}
df<- read.csv("genus_seawater.csv", row.names=1)

data = t(df)

groups <- read.csv("metadata_seawater.csv")


data <- vegdist(data)

length=length(unique(as.character(groups$sample)))
times1=length%/%8
res1=length%%8
times2=length%/%5
res2=length%%5
col1=rep(1:8,times1)
col=c(col1,1:res1)
pich1=rep(c(21:24),times2)
pich=c(pich1,15:(15+res2))
pcoa<- pcoa(data, correction = "none", rn = NULL)
PC1 = pcoa$vectors[,1]
PC2 = pcoa$vectors[,2]

plotdata <- data.frame(rownames(pcoa$vectors),PC1,PC2,groups$Carrier)

colnames(plotdata) <-c("sample","PC1","PC2","Group")
pc1 <-floor(pcoa$values$Relative_eig[1]*100)
pc2 <-floor(pcoa$values$Relative_eig[2]*100)
plotdata$Group <- factor(plotdata$Group)



library(dplyr)
yf <- plotdata
yd1 <- yf %>% group_by(Group) %>% summarise(Max = max(PC1))
yd2 <- yf %>% group_by(Group) %>% summarise(Max = max(PC2))
yd1$Max <- yd1$Max + max(yd1$Max)*0.1
yd2$Max <- yd2$Max + max(yd2$Max)*0.1

fit1 <- aov(PC1~Group,data = plotdata)



otu.adonis=adonis(data~Carrier,data = groups,distance = "bray")



library(multcomp)

tuk1<-glht(fit1,linfct=mcp(Group="Tukey"))
res1 <- cld(tuk1,alpah=0.05)

fit2 <- aov(PC2~Group,data = plotdata)
tuk2<-glht(fit2,linfct=mcp(Group="Tukey"))
res2 <- cld(tuk2,alpah=0.05)


test <- data.frame(PC1 = res1$mcletters$Letters,PC2 = res2$mcletters$Letters,
                   yd1 = yd1$Max,yd2 = yd2$Max,Group = yd1$Group)
test$Group <- factor(test$Group)



lccol2 = palette.colors(palette = "Set1")
lccol2 =c("#377EB8", "#E41A1C")

```



```{r pressure, echo=FALSE}
p1 <- ggplot(plotdata,aes(x = Group, y = PC1, color = Group)) +
  
  geom_boxplot() +
  
  geom_jitter(position=position_jitter(0.25),size= 0.2, alpha=1, shape = 19) +
  
  geom_text(data = test,aes(x = Group,y = yd1,label = PC1)) +
  
  coord_flip() +
  
  scale_color_manual(values = lccol2) +
  
  theme_minimal()+
  
  theme(legend.position = "none")+
  
  theme(axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.x=element_blank(),
        legend.position = "none")




p3 <- ggplot(plotdata,aes(x = Group, y = PC2, color = Group)) +
  
  geom_boxplot(aes(color = Group)) +
  
  geom_jitter(position=position_jitter(0.25),size= 0.2, alpha=1, shape = 19) +
  
  geom_text(data = test,aes(x = Group,y = yd2,label = PC2)) +
  
  scale_color_manual(values = lccol2) +
  
  theme_minimal()+
  
  theme(legend.position = "none")+
  
  theme(axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5))




p2<-ggplot(plotdata, aes(PC1, PC2)) +
  
  geom_point(aes(color=Group),size=0.3,pch = 19,alpha=1)+
  
  scale_color_manual(values = lccol2)+
  
  xlab(paste("PC1 ( ",pc1,"%"," )",sep="")) + 
  
  ylab(paste("PC2 ( ",pc2,"%"," )",sep=""))+
  
  xlim(ggplot_build(p1)$layout$panel_scales_y[[1]]$range$range) +
  
  ylim(ggplot_build(p3)$layout$panel_scales_y[[1]]$range$range) +
  
  theme(text=element_text(size=30))+
  
  theme_minimal() + theme(legend.key=element_blank(),legend.position = "none",
                     legend.background = element_rect(colour = "black"))+
  
  guides(fill = guide_legend(ncol = 1))





p4 <- ggplot(plotdata, aes(PC1, PC2)) +
  
  geom_text(aes(x = -0.5,y = 0.6,
                label = paste("PERMANOVA",otu.adonis$aov.tab$Df[1],
                              "\nR2 = ",round(otu.adonis$aov.tab$R2[1],4),
                              "\np-value = ",otu.adonis$aov.tab$`Pr(>F)`[1],sep = "")),size = 3) +
  
  theme_minimal() +
  
  xlab("") + ylab("") +
  
  theme(axis.title = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.grid = element_blank(), 
        panel.border = element_blank())



library(patchwork)

p5 <- p1 + p4 + p2 + p3 + 
  plot_layout(heights = c(1,4),widths = c(4,1),ncol = 2,nrow = 2)


p5

ggsave(plot = p5, "PCoA_seawater.pdf", height = 96, width = 100, units = "mm")

```



